###############################################################################
#
# Config for a Qemu VM hosted on a MacBook Pro M1 with UTM.
#
###############################################################################

{ config, lib, pkgs, ... }:
{
  imports = [
    ./hardware-configuration.nix       # Generated by nix at install
    ../../system                       # Shared settings/defaults for all hosts
  ];

  config = {
    # Custom options
    nouveauxParadigmes = {
      hostname            = "utm";
      system              = "aarch64-linux";
      rootDisk            = "/dev/vda";
      impermanence.enable = true;
    };
  };


  # Qemu/UTM specific packages
  environment.systemPackages = with pkgs; [
    # ...
  ];


  # It's a VM so no need for that
  networking.wireless.enable = false;
}

