signal_db_path = "/home/unnamedplayer/.local/share/gurk/signal-db"
first_name_only = false
show_receipts = true
notifications = true
bell = true
colored_messages = false
default_keybindings = true

[user]
name = "Karl"
phone_number = "+32498139866"

[sqlite]
url = "sqlite:///home/unnamedplayer/.local/share/gurk/gurk.sqlite"
_preserve_unencryped = false

[keybindings]
