###############################################################################
#
# Config for q3dm11.
#
# This is an old Sony Vaio VGN-TX5XN/B from like 2005 or so,
#   Intel U1500, 1.5GB RAM and something like 100GB on hdd.
#
# Single user host, tty only.
# 
###############################################################################

{ config, pkgs, ... }:
{
  imports = [
    ./hardware-configuration.nix       # Generated by nix at install
    ../../system                       # Shared settings/defaults for all hosts
  ];

  config = {
    # Custom options
    nouveauxParadigmes = {
      hostname            = "q3dm11";
      cpuFlavor           = "intel";
      rootDisk            = "/dev/sda";
      encryption.enable   = true;
      impermanence.enable = true;
      gui.enable          = false;
      stateVersion        = "23.11";
    };

    # Host specific packages
    environment.systemPackages = with pkgs; [
      # ...
    ];
  };
}
